# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['vat_validator_gui.py'],
    pathex=[],
    binaries=[],
    datas=[('document_processor.py', '.')],
    hiddenimports=[
        'document_processor',
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.worksheet',
        'openpyxl.styles',
        'requests',
        'PyQt5.QtCore',
        'PyQt5.QtWidgets',
        'PyQt5.QtGui',
        'concurrent.futures',
        'threading',
        'datetime',
        'json',
        'time',
        'shutil',
        'os',
        'sys',
        'pandas',
        'pandas.core',
        'pandas.core.arrays',
        'pandas.core.dtypes',
        'pandas.io',
        'pandas.io.excel',
        'pandas.io.common',
        'pandas.io.parsers',
        'pandas._libs',
        'pandas._libs.tslibs',
        'docx',
        'docx.document',
        'docx.shared',
        'docx.enum',
        'docx.enum.text',
        'docx.oxml',
        'docx.oxml.parser',
        'docx.oxml.ns',
        'logging',
        'typing'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='VAT验证工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='favicon.ico',  # Windows使用ICO图标文件
)
