name: Build Windows EXE

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  release:
    types: [ created ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build EXE with PyInstaller
      run: |
        echo "检查spec文件是否存在..."
        if (Test-Path "VAT验证工具-Windows.spec") {
          echo "使用Windows专用spec文件"
          pyinstaller "VAT验证工具-Windows.spec"
        } else {
          echo "Windows专用spec文件不存在，使用默认spec文件"
          pyinstaller "VAT验证工具.spec"
        }
    
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: VAT验证工具-Windows-EXE
        path: dist/VAT验证工具.exe
    
    - name: Upload to Release (if release)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/VAT验证工具.exe
        asset_name: VAT验证工具-${{ github.event.release.tag_name }}.exe
        asset_content_type: application/octet-stream

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pyqt5
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Linux executable
      run: |
        pyinstaller "VAT验证工具-Linux.spec"
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: VAT验证工具-Linux
        path: dist/VAT验证工具

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build macOS app
      run: |
        pyinstaller "VAT验证工具.spec"
    
    - name: Upload macOS artifact
      uses: actions/upload-artifact@v4
      with:
        name: VAT验证工具-macOS
        path: dist/VAT验证工具.app